#include <stdio.h>
#include "parser.h"

#define INIT_JUNCTION(_prev_state, _token_type, _next_state) \
{ \
	if (token.type == _token_type && parser->state == _prev_state) \
	{ \
		parser->state = _next_state; \
		return; \
	} \
}

void parse(parser_t *parser, token_t token, int *is_error)
{
	INIT_JUNCTION(STATE_INVALID, IDENT, STATE_CLASS_ID);
	INIT_JUNCTION(STATE_CLASS_ID, IDENT, STATE_OPER_ID);
	INIT_JUNCTION(STATE_OPER_ID, EQUALS, STATE_EQUALS);
	INIT_JUNCTION(STATE_EQUALS, OPEN_PAREN, STATE_OPEN_PAREN);
	//INIT_JUNCTION(STATE_OPEN_PAREN, IDENT, STATE_IDENT);
	INIT_JUNCTION(STATE_OPEN_PAREN, IDENT, STATE_IDENT);
	INIT_JUNCTION(STATE_PARAMS_ID, COMMA, STATE_COMMA);
	INIT_JUNCTION(STATE_PARAMS_ID, CLOSE_PAREN, STATE_CLOSE_PAREN);
	INIT_JUNCTION(STATE_OPEN_PAREN, CLOSE_PAREN, STATE_CLOSE_PAREN);
	INIT_JUNCTION(STATE_CLOSE_PAREN, ASSIGNMENT, STATE_ASSIGNMENT);
	INIT_JUNCTION(STATE_ASSIGNMENT, IDENT, STATE_IDENT);
	INIT_JUNCTION(STATE_ASSIGNMENT, OPEN_BRACE, STATE_OPEN_BRACE);
	INIT_JUNCTION(STATE_ASSIGNMENT, NUMBER, STATE_NUMBER);
	INIT_JUNCTION(STATE_IDENT, IDENT, STATE_OPERATION);
	INIT_JUNCTION(STATE_OPERATION, NUMBER, STATE_NUMBER);
	INIT_JUNCTION(STATE_OPERATION, IDENT, STATE_IDENT);
	INIT_JUNCTION(STATE_NUMBER, OPERATION, STATE_OPERATION);
	INIT_JUNCTION(STATE_IDENT, OPERATION, STATE_OPERATION);
	INIT_JUNCTION(STATE_NUMBER, CLOSE_BRACE, STATE_CLOSE_BRACE);
	INIT_JUNCTION(STATE_IDENT, CLOSE_BRACE, STATE_CLOSE_BRACE);
	INIT_JUNCTION(STATE_NUMBER, SEMICOLON, STATE_SEMICOLON);
	INIT_JUNCTION(STATE_IDENT, SEMICOLON, STATE_SEMICOLON);
	INIT_JUNCTION(STATE_SEMICOLON, NEWLINE, STATE_INVALID);
	INIT_JUNCTION(STATE_SEMICOLON, WHITESPACE, STATE_INVALID);

	if (token.type ==  WHITESPACE)
		return;
	*is_error = 1;
	parser->state = INVALID;

}
