#include <stdio.h>
#include "parser.h"

#define INIT_VALID_STATE(_state, _type) \
{ \
	if (token.type == _type && parser->state == _state) \
	{ \
		parser->state = _type; \
		return; \
	} \
}

void parse(parser_t *parser, token_t token, int *is_error)
{
	INIT_VALID_STATE(INVALID, KEYWORD);
	INIT_VALID_STATE(KEYWORD, IDENT);
	INIT_VALID_STATE(IDENT, EQUALS);
	INIT_VALID_STATE(EQUALS, OPEN_PAREN);
	INIT_VALID_STATE(OPEN_PAREN, KEYWORD);
	INIT_VALID_STATE(OPEN_PAREN, CLOSE_PAREN);
	INIT_VALID_STATE(CLOSE_PAREN, ASSIGNMENT);
	INIT_VALID_STATE(ASSIGNMENT, OPEN_BRACE);
	INIT_VALID_STATE(ASSIGNMENT, IDENT);
	INIT_VALID_STATE(OPEN_BRACE, IDENT);
	INIT_VALID_STATE(OPEN_BRACE, CLOSE_BRACE);
	INIT_VALID_STATE(OPEN_BRACE, KEYWORD);
	INIT_VALID_STATE(IDENT, OPERATION);
	INIT_VALID_STATE(IDENT, CLOSE_PAREN);
	INIT_VALID_STATE(OPERATION, IDENT);
	INIT_VALID_STATE(CLOSE_BRACE, SEMICOLON);
	INIT_VALID_STATE(OPERATION, NUMBER);
	INIT_VALID_STATE(OPERATION, IDENT);
	INIT_VALID_STATE(IDENT, CLOSE_BRACE);
	INIT_VALID_STATE(NUMBER, CLOSE_BRACE);
	INIT_VALID_STATE(NUMBER, OPERATION);
	INIT_VALID_STATE(IDENT, COMMA);	
	INIT_VALID_STATE(COMMA, KEYWORD);
	
	if (token.type ==  WHITESPACE)
		return;
	*is_error = 1;
	parser->state = INVALID;

}
